"use client";

import {
  generateCoverImageAction,
  listWechatConnectionsAction,
  listWechatSyncLogsAction,
  refreshKnowledgeCardAction,
  selectCoverCandidateAction,
  upsertWechatConnectionAction,
} from "@/app/(writer)/writer-actions";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { startTransition, useMemo } from "react";
import { resolveArticleMainStepNavigationAccess } from "@/lib/article-workspace-step-navigation";
import { formatPlanDisplayName } from "@/lib/plan-labels";
import {
  isArticleMainStepCode,
  type ArticleMainStepCode,
} from "@/lib/article-workflow-registry";
import type { ArticleStatus } from "@/lib/domain";
import {
  formatWorkspaceViewLabel,
} from "./article-workspace/authoring-phase";
import {
  buildEvidenceItemSignature,
  getStageApplyButtonLabel,
  type StageArtifactItem,
  type StrategyCardItem,
  upsertStageArtifact,
} from "./article-workspace/article-workspace-client-data";
import { createArticleWorkspaceEvidenceActions } from "./article-workspace/article-workspace-evidence-actions";
import { buildArticleWorkspaceActionBundle } from "./article-workspace/article-workspace-action-bundle";
import { buildArticleWorkspaceActionBundleInput } from "./article-workspace/article-workspace-action-bundle-input";
import { useArticleWorkspaceClientComputed } from "./article-workspace/article-workspace-client-computed";
import { ArticleWorkspaceFrame } from "./article-workspace/article-workspace-frame";
import {
  OUTCOME_WINDOWS,
  type ArticleEditorClientProps,
  type ArticleImagePromptItem,
  type ArticleOutcomeBundleItem,
} from "./article-workspace/article-workspace-client-types";
import {
  type RecentSyncLogItem,
  type WechatConnectionItem,
} from "./article-workspace/article-workspace-publish-actions";
import { buildArticleWorkspaceShellBundle } from "./article-workspace/article-workspace-shell-bundle";
import { useArticleWorkspaceClientState } from "./article-workspace/article-workspace-client-state";
import { createArticleWorkspaceStrategyActions } from "./article-workspace/article-workspace-strategy-actions";
import { createArticleWorkspaceStrategyState } from "./article-workspace/article-workspace-strategy-state";
import { buildArticleWorkspaceDerivedState } from "./article-workspace/article-workspace-derived-state";
import { useArticleWorkspaceLocalEffects } from "./article-workspace/article-workspace-local-effects";
import { copyTextToClipboard, createDataUrlFileChangeHandler } from "./article-workspace/article-workspace-local-handlers";
import { buildArticleWorkspaceShellDerivedState } from "./article-workspace/article-workspace-shell-derived-state";
import { useArticleWorkspaceSyncEffects } from "./article-workspace/article-workspace-sync-effects";
import { buildArticleWorkspaceStagePanelProps } from "./article-workspace/article-workspace-stage-panel-props";
import { createArticleWorkspaceWorkflowActions } from "./article-workspace/article-workspace-workflow-actions";
import { useCommandMenu } from "./command-menu";
import type { ImaEvidenceSelection } from "./ima-evidence-search-drawer";

const MAX_EVIDENCE_ITEMS = 20;

const ARTICLE_AUTOSAVE_DEBOUNCE_MS = 500;

function refreshRouter(router: ReturnType<typeof useRouter>) {
  startTransition(() => {
    router.refresh();
  });
}

export function ArticleEditorClient({
  article,
  seriesOptions,
  nodes: initialNodes,
  fragments: initialFragments,
  languageGuardRules,
  connections: initialConnections,
  snapshots: initialSnapshots,
  templates,
  recentSyncLogs,
  recentArticles,
  recentDeepWritingStates,
  initialStrategyCard,
  initialEvidenceItems,
  initialOutcomeBundle,
  workflow: initialWorkflow,
  stageArtifacts: initialStageArtifacts,
  knowledgeCards,
  canExportPdf,
  canGenerateCoverImage,
  canUseCoverImageReference,
  canUseHistoryReferences,
  canPublishToWechat,
  planName,
  authoringContext,
  seriesInsight,
  currentSeriesPlaybook,
  effectiveWritingProfile,
  coverImageQuota: initialCoverImageQuota,
  imageAssetQuota: initialImageAssetQuota,
  initialCoverImageCandidates,
  initialImagePrompts,
  initialCoverImage,
}: ArticleEditorClientProps) {
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const requestedMainStepCode: ArticleMainStepCode | null = (() => {
    const rawStep = searchParams.get("step");
    return rawStep && isArticleMainStepCode(rawStep) ? rawStep : null;
  })();
  const { theme, focusMode: isFocusMode, toggleTheme, toggleFocusMode } = useCommandMenu();
  const displayPlanName = formatPlanDisplayName(planName);
  const {
    title,
    setTitle,
    markdown,
    setMarkdown,
    htmlPreview,
    setHtmlPreview,
    status,
    setStatus,
    seriesId,
    setSeriesId,
    wechatTemplateId,
    setWechatTemplateId,
    nodes,
    setNodes,
    fragmentPool,
    setFragmentPool,
    wechatConnections,
    setWechatConnections,
    syncLogs,
    setSyncLogs,
    strategyCard,
    setStrategyCard,
    evidenceItems,
    setEvidenceItems,
    evidenceDraftItems,
    setEvidenceDraftItems,
    articleOutcomeBundle,
    setArticleOutcomeBundle,
    knowledgeCardItems,
    setKnowledgeCardItems,
    workflow,
    setWorkflow,
    stageArtifacts,
    setStageArtifacts,
    view,
    setView,
    selectedConnectionId,
    setSelectedConnectionId,
    snapshots,
    setSnapshots,
    snapshotNote,
    setSnapshotNote,
    requestedMainStepHandledRef,
    diffState,
    setDiffState,
    saveState,
    setSaveState,
    message,
    setMessage,
    generating,
    setGenerating,
    coverImage,
    setCoverImage,
    coverImageCandidates,
    setCoverImageCandidates,
    coverImageQuota,
    setCoverImageQuota,
    imageAssetQuota,
    setImageAssetQuota,
    imagePrompts,
    setImagePrompts,
    coverImageReferenceDataUrl,
    setCoverImageReferenceDataUrl,
    generatingCover,
    setGeneratingCover,
    selectingCoverCandidateId,
    setSelectingCoverCandidateId,
    savingImagePrompts,
    setSavingImagePrompts,
    generatingInlineImages,
    setGeneratingInlineImages,
    insertingVisualAssets,
    setInsertingVisualAssets,
    publishing,
    setPublishing,
    retryingPublish,
    setRetryingPublish,
    loadingDiffId,
    setLoadingDiffId,
    refreshingKnowledgeId,
    setRefreshingKnowledgeId,
    expandedKnowledgeCardId,
    setExpandedKnowledgeCardId,
    highlightedKnowledgeCardId,
    setHighlightedKnowledgeCardId,
    updatingWorkflowCode,
    setUpdatingWorkflowCode,
    generatingStageArtifactCode,
    setGeneratingStageArtifactCode,
    applyingStageArtifactCode,
    setApplyingStageArtifactCode,
    syncingOutlineArtifact,
    setSyncingOutlineArtifact,
    savingAudienceSelection,
    setSavingAudienceSelection,
    applyingLayout,
    setApplyingLayout,
    loadingPublishPreview,
    setLoadingPublishPreview,
    refreshingPublishPreview,
    setRefreshingPublishPreview,
    deepWritingPrototypeOverride,
    setDeepWritingPrototypeOverride,
    deepWritingStateVariantOverride,
    setDeepWritingStateVariantOverride,
    deepWritingOpeningPreviewLoadingKey,
    setDeepWritingOpeningPreviewLoadingKey,
    deepWritingOpeningPreviews,
    setDeepWritingOpeningPreviews,
    deepWritingOpeningCheckLoading,
    setDeepWritingOpeningCheckLoading,
    publishPreview,
    setPublishPreview,
    pendingPublishIntent,
    setPendingPublishIntent,
    factCheckEvidenceUrl,
    setFactCheckEvidenceUrl,
    addingFactCheckEvidence,
    setAddingFactCheckEvidence,
    factCheckEvidenceIssue,
    setFactCheckEvidenceIssue,
    recentFactCheckEvidenceIssues,
    setRecentFactCheckEvidenceIssues,
    factCheckRetryableCount,
    factCheckRecoveredCount,
    showMobileInspector,
    setShowMobileInspector,
    showWechatConnectModal,
    setShowWechatConnectModal,
    wechatConnectSubmitting,
    setWechatConnectSubmitting,
    continuePublishAfterWechatConnect,
    setContinuePublishAfterWechatConnect,
    wechatConnectAccountName,
    setWechatConnectAccountName,
    wechatConnectOriginalId,
    setWechatConnectOriginalId,
    wechatConnectAppId,
    setWechatConnectAppId,
    wechatConnectAppSecret,
    setWechatConnectAppSecret,
    wechatConnectIsDefault,
    setWechatConnectIsDefault,
    wechatConnectMessage,
    setWechatConnectMessage,
    selectedOutcomeWindowCode,
    setSelectedOutcomeWindowCode,
    outcomeReadCount,
    setOutcomeReadCount,
    outcomeShareCount,
    setOutcomeShareCount,
    outcomeLikeCount,
    setOutcomeLikeCount,
    outcomeNotes,
    setOutcomeNotes,
    outcomeTargetPackage,
    setOutcomeTargetPackage,
    outcomeHitStatus,
    setOutcomeHitStatus,
    outcomeExpressionFeedback,
    setOutcomeExpressionFeedback,
    outcomeReviewSummary,
    setOutcomeReviewSummary,
    outcomeNextAction,
    setOutcomeNextAction,
    outcomePlaybookTagsInput,
    setOutcomePlaybookTagsInput,
    savingOutcomeSnapshot,
    setSavingOutcomeSnapshot,
    seriesPlaybook,
    setSeriesPlaybook,
    loadingSeriesPlaybook,
    setLoadingSeriesPlaybook,
    audienceSelectionDraft,
    setAudienceSelectionDraft,
    outlineSelectionDraft,
    setOutlineSelectionDraft,
    outlineMaterials,
    setOutlineMaterials,
    loadingOutlineMaterials,
    setLoadingOutlineMaterials,
    savingOutlineMaterials,
    setSavingOutlineMaterials,
    strategyTargetReader,
    setStrategyTargetReader,
    strategyCoreAssertion,
    setStrategyCoreAssertion,
    strategyWhyNow,
    setStrategyWhyNow,
    strategyArchetype,
    setStrategyArchetype,
    strategyMainstreamBelief,
    setStrategyMainstreamBelief,
    strategyResearchHypothesis,
    setStrategyResearchHypothesis,
    strategyMarketPositionInsight,
    setStrategyMarketPositionInsight,
    strategyHistoricalTurningPoint,
    setStrategyHistoricalTurningPoint,
    strategyTargetPackage,
    setStrategyTargetPackage,
    strategyPublishWindow,
    setStrategyPublishWindow,
    strategyEndingAction,
    setStrategyEndingAction,
    strategyFirstHandObservation,
    setStrategyFirstHandObservation,
    strategyFeltMoment,
    setStrategyFeltMoment,
    strategyWhyThisHitMe,
    setStrategyWhyThisHitMe,
    strategyRealSceneOrDialogue,
    setStrategyRealSceneOrDialogue,
    strategyWantToComplain,
    setStrategyWantToComplain,
    strategyNonDelegableTruth,
    setStrategyNonDelegableTruth,
    strategyViewMode,
    setStrategyViewMode,
    savingStrategyCard,
    setSavingStrategyCard,
    auditingStrategyCard,
    setAuditingStrategyCard,
    lockingStrategyCard,
    setLockingStrategyCard,
    reversingStrategyCardDimension,
    setReversingStrategyCardDimension,
    savingEvidenceItems,
    setSavingEvidenceItems,
    taggingEvidenceItems,
    setTaggingEvidenceItems,
    showImaEvidenceDrawer,
    setShowImaEvidenceDrawer,
    strategyCardDraft,
    strategyFourPointDrafts,
    setStrategyFourPointDrafts,
    strategyCardMissingFields,
    savedStrategyCardMissingFields,
    strategyCardIsComplete,
    savedStrategyCardIsComplete,
    strategyCardHasUnsavedChanges,
    supplementalViewpointsDraft,
    setSupplementalViewpointsDraft,
    outlineMaterialNodeId,
    setOutlineMaterialNodeId,
    outlineMaterialFragmentId,
    setOutlineMaterialFragmentId,
    outlineMaterialUsageMode,
    setOutlineMaterialUsageMode,
    outlineMaterialCreateMode,
    setOutlineMaterialCreateMode,
    outlineMaterialTitle,
    setOutlineMaterialTitle,
    outlineMaterialContent,
    setOutlineMaterialContent,
    outlineMaterialUrl,
    setOutlineMaterialUrl,
    outlineMaterialImageDataUrl,
    setOutlineMaterialImageDataUrl,
    outlineMaterialScreenshotFileName,
    setOutlineMaterialScreenshotFileName,
    factCheckSelectionDraft,
    setFactCheckSelectionDraft,
    historyReferenceSuggestions,
    setHistoryReferenceSuggestions,
    selectedHistoryReferences,
    setSelectedHistoryReferences,
    loadingHistoryReferences,
    setLoadingHistoryReferences,
    savingHistoryReferences,
    setSavingHistoryReferences,
    lastSavedRef,
    outlineMaterialScreenshotInputRef,
  } = useArticleWorkspaceClientState({
    article,
    seriesOptions,
    initialNodes,
    initialFragments,
    initialConnections,
    initialSnapshots,
    recentSyncLogs,
    initialStrategyCard,
    initialEvidenceItems,
    initialOutcomeBundle,
    initialWorkflow,
    initialStageArtifacts,
    knowledgeCards,
    currentSeriesPlaybook,
    initialCoverImageQuota,
    initialImageAssetQuota,
    initialCoverImageCandidates,
    initialImagePrompts,
    initialCoverImage,
  });
  const currentSearchParams = searchParams.toString();

  const {
    bannedWords,
    detectedBannedWords,
    liveLanguageGuardHits,
    liveLanguageGuardSummary,
    editorialReview,
    selectedTemplate,
    selectedSeries,
    latestSyncLog,
    currentArticleOutcome,
  } = useArticleWorkspaceClientComputed({
    templates,
    wechatTemplateId,
    seriesOptions,
    seriesId,
    syncLogs,
    articleOutcomeBundle,
    languageGuardRules,
    markdown,
  });
  const {
    selectedConnection,
    currentOutcomeSnapshot,
    visualSuggestion,
    outlineMaterialReadiness,
    articleScorecardSummary,
    articleOutcomeAttributionSummary,
    audienceArtifact,
    outlineArtifact,
    deepWritingArtifact,
    factCheckArtifact,
    prosePolishArtifact,
    researchArtifact,
    currentStage,
    currentArticleMainStep,
    currentStageArtifact,
    currentStagePayload,
    currentAudienceSelection,
    currentOutlineSelection,
    currentFactCheckSelection,
    audienceSelectionState,
    outlineSelectionState,
    liveAiNoise,
    activeAiNoiseRecord,
    activeAiNoiseScore,
    historyPlanCount,
    strategySuggestedValues,
    suggestedEvidenceItems,
    evidenceDraftStats,
    savedEvidenceStats,
    editorDiversityReport,
    editorQualityPanel,
    prosePolishWeakestLayer,
    prosePolishSelectedTitle,
    prosePolishOutlinePayload,
    evidenceHasUnsavedChanges,
    outlineGapHintsForGuide,
    titleConfirmedForGuide,
    factCheckReady,
    prosePolishReady,
    researchTimelineCountForGuide,
    researchComparisonCountForGuide,
    researchInsightCountForGuide,
    researchCoverageSufficiencyForGuide,
    researchGenerationGate,
    generateBlockedByResearch,
    generateBlockedMessage,
    researchStepSummary,
    researchCoverageRibbon,
  } = useMemo(
    () =>
      buildArticleWorkspaceDerivedState({
        article,
        title,
        markdown,
        status,
        authoringContext,
        wechatConnections,
        selectedConnectionId,
        articleOutcomeBundle,
        selectedOutcomeWindowCode,
        nodes,
        outlineMaterials,
        stageArtifacts,
        workflow,
        selectedSeries,
        seriesInsight,
        strategyCard,
        strategyCardDraft,
        outcomeTargetPackage,
        evidenceDraftItems,
        evidenceItems,
        recentArticles,
        recentDeepWritingStates,
        liveLanguageGuardHitsCount: liveLanguageGuardHits.length,
      }),
    [
      article,
      articleOutcomeBundle,
      authoringContext,
      evidenceDraftItems,
      evidenceItems,
      liveLanguageGuardHits.length,
      markdown,
      nodes,
      outlineMaterials,
      outcomeTargetPackage,
      recentArticles,
      recentDeepWritingStates,
      selectedConnectionId,
      selectedOutcomeWindowCode,
      selectedSeries,
      seriesInsight,
      stageArtifacts,
      status,
      strategyCard,
      strategyCardDraft,
      title,
      wechatConnections,
      workflow,
    ],
  );
  const prosePolishRegeneratingTitles = generatingStageArtifactCode === "outlinePlanning";
  const {
    editorStageChecklist,
    articleMainSteps,
    currentArticleMainStepDisplay,
    currentAuthoringPhase,
    authoringPhases,
    hasDraftContent,
    hasPreviewContent,
    currentArticleLabel,
    draftStarterOptions,
    draftBlankSlate,
    draftBlankSlateInspirations,
    workspaceBlankSlate,
    reviewBlankSlate,
    knowledgeBlankSlate,
    isCollectPhase,
    isThinkPhase,
    isWritePhase,
    isPolishPhase,
    showLeftWorkspaceRail,
    showResearchChecklistRail,
    showKnowledgeCardsRail,
    showLanguageGuardRail,
    showVisualEngineRail,
    showDeliveryRail,
    showCompactSixStepRail,
    showMobileInspectorEntry,
    currentAuthoringPhaseHint,
    workspaceGridClass,
    planCapabilityHints,
    currentStageAction,
    coverImageLimitReached,
    imageAssetStorageLimitReached,
    canShowWechatControls,
    hasUnsavedWechatRenderInputs,
    currentArticleTask,
    coverImageButtonDisabled,
    coverImageButtonLabel,
    nodeVisualSuggestions,
  } = useMemo(
    () =>
      buildArticleWorkspaceShellDerivedState({
        article,
        title,
        markdown,
        htmlPreview,
        currentArticleMainStep,
        workflowCurrentStageCode: workflow.currentStageCode,
        currentStage,
        outlineArtifact,
        deepWritingArtifact,
        researchArtifact,
        selectedConnection,
        latestSyncLog,
        canPublishToWechat,
        canUseHistoryReferences,
        canGenerateCoverImage,
        canUseCoverImageReference,
        canExportPdf,
        displayPlanName,
        coverImage,
        coverImageQuota,
        imageAssetQuota,
        generatingCover,
        titleConfirmedForGuide,
        researchCoverageSufficiencyForGuide,
        researchInsightCountForGuide,
        researchTimelineCountForGuide,
        researchComparisonCountForGuide,
        generateBlockedByResearch,
        generateBlockedMessage,
        outlineGapHintsForGuide,
        outlineMaterialReadiness,
        evidenceDraftStats,
        savedEvidenceStats,
        evidenceHasUnsavedChanges,
        factCheckReady,
        prosePolishReady,
        activeAiNoiseScore,
        historyPlanCount,
        articleOutcomeMissingWindowCodes: articleOutcomeBundle.missingWindowCodes,
        currentArticleOutcomeHitStatus: currentArticleOutcome?.hitStatus ?? "pending",
        strategyCardIsComplete,
        strategyCardHasUnsavedChanges,
        strategyCardMissingFields,
        savedStrategyCardIsComplete,
        savedStrategyCardMissingFields,
        liveLanguageGuardHitsCount: liveLanguageGuardHits.length,
        fragmentPool,
        isFocusMode,
        nodes,
        authoringContext,
        status,
        wechatTemplateId,
        lastSavedTitle: lastSavedRef.current.title,
        lastSavedMarkdown: lastSavedRef.current.markdown,
        lastSavedWechatTemplateId: lastSavedRef.current.wechatTemplateId,
      }),
    [
      activeAiNoiseScore,
      article,
      articleOutcomeBundle.missingWindowCodes,
      authoringContext,
      canExportPdf,
      canGenerateCoverImage,
      canPublishToWechat,
      canUseCoverImageReference,
      canUseHistoryReferences,
      coverImage,
      coverImageQuota,
      currentArticleMainStep,
      currentArticleOutcome?.hitStatus,
      currentStage,
      deepWritingArtifact,
      displayPlanName,
      evidenceDraftStats,
      evidenceHasUnsavedChanges,
      factCheckReady,
      fragmentPool,
      generatingCover,
      generateBlockedByResearch,
      generateBlockedMessage,
      historyPlanCount,
      htmlPreview,
      imageAssetQuota,
      isFocusMode,
      latestSyncLog,
      liveLanguageGuardHits.length,
      markdown,
      nodes,
      outlineArtifact,
      outlineGapHintsForGuide,
      outlineMaterialReadiness,
      prosePolishReady,
      researchArtifact,
      researchComparisonCountForGuide,
      researchCoverageSufficiencyForGuide,
      researchInsightCountForGuide,
      researchTimelineCountForGuide,
      savedEvidenceStats,
      savedStrategyCardIsComplete,
      savedStrategyCardMissingFields,
      selectedConnection,
      status,
      strategyCardHasUnsavedChanges,
      strategyCardIsComplete,
      strategyCardMissingFields,
      title,
      titleConfirmedForGuide,
      wechatTemplateId,
      workflow.currentStageCode,
    ],
  );
  const resolveMainStepAccess = useMemo(
    () =>
      (stepCode: string) =>
        resolveArticleMainStepNavigationAccess({
          targetStepCode: isArticleMainStepCode(stepCode) ? stepCode : currentArticleMainStep.code,
          currentStepCode: currentArticleMainStep.code,
          canOpenResultStep: status === "published",
          generateBlockedByResearch,
          generateBlockedMessage,
        }),
    [
      currentArticleMainStep.code,
      generateBlockedByResearch,
      generateBlockedMessage,
      status,
    ],
  );
  const {
    updateWorkflow,
    handleArticleMainStepSelect,
    goToResearchStep,
  } = createArticleWorkspaceWorkflowActions({
    articleId: article.id,
    status,
    setUpdatingWorkflowCode,
    setWorkflow,
    setView,
    setMessage,
    resolveMainStepAccess,
  });
  const guardedArticleMainSteps = useMemo(
    () =>
      articleMainSteps.map((step) => {
        const access = resolveArticleMainStepNavigationAccess({
          targetStepCode: step.code,
          currentStepCode: currentArticleMainStep.code,
          canOpenResultStep: status === "published",
          generateBlockedByResearch,
          generateBlockedMessage,
        });
        return {
          ...step,
          disabled: access.disabled,
          disabledReason: access.reason,
        };
      }),
    [
      articleMainSteps,
      currentArticleMainStep.code,
      generateBlockedByResearch,
      generateBlockedMessage,
      status,
    ],
  );
  const handleOutlineMaterialScreenshotFileChange = createDataUrlFileChangeHandler({
    onEmpty: () => {
      setOutlineMaterialImageDataUrl(null);
      setOutlineMaterialScreenshotFileName("");
    },
    onLoaded: (result, fileName) => {
      setOutlineMaterialImageDataUrl(result);
      setOutlineMaterialScreenshotFileName(fileName);
    },
  });

  const { commitSavedStrategyCard } = createArticleWorkspaceStrategyState({
    strategyCard,
    outcomeTargetPackage,
    setStrategyCard,
    setOutcomeTargetPackage,
    setPublishPreview: () => setPublishPreview(null),
    refreshRouter: () => refreshRouter(router),
    setStrategyArchetype,
    setStrategyMainstreamBelief,
    setStrategyTargetReader,
    setStrategyCoreAssertion,
    setStrategyWhyNow,
    setStrategyResearchHypothesis,
    setStrategyMarketPositionInsight,
    setStrategyHistoricalTurningPoint,
    setStrategyTargetPackage,
    setStrategyPublishWindow,
    setStrategyEndingAction,
    setStrategyFirstHandObservation,
    setStrategyFeltMoment,
    setStrategyWhyThisHitMe,
    setStrategyRealSceneOrDialogue,
    setStrategyWantToComplain,
    setStrategyNonDelegableTruth,
  });

  const {
    persistStrategyCardDraft,
    applyResearchWritebackToStrategyCard,
    runStrategyAudit,
    lockStrategyCard,
    applyStrategyFourPointReverseWriteback,
  } = createArticleWorkspaceStrategyActions({
    articleId: article.id,
    strategyCardDraft,
    strategyFourPointDrafts,
    setSavingStrategyCard,
    setMessage,
    commitSavedStrategyCard,
    setAuditingStrategyCard,
    setLockingStrategyCard,
    confirm: (content) => window.confirm(content),
    setReversingStrategyCardDimension,
  });

  const {
    toggleEvidenceDraftItem,
    appendImaEvidenceItems,
    toggleEvidenceDraftHookTag,
    updateEvidenceDraftHookStrength,
    persistEvidenceItems,
    applyResearchSuggestedEvidence,
    autoTagEvidenceItems,
  } = createArticleWorkspaceEvidenceActions({
    articleId: article.id,
    maxEvidenceItems: MAX_EVIDENCE_ITEMS,
    evidenceDraftItems,
    evidenceHasUnsavedChanges,
    savedEvidenceReady: savedEvidenceStats.ready,
    setEvidenceDraftItems,
    setEvidenceItems,
    setSavingEvidenceItems,
    setTaggingEvidenceItems,
    setMessage,
    setPublishPreview,
    refreshRouter: () => refreshRouter(router),
  });

  const {
    saveArticleDraft,
    generate,
    generateStageArtifact,
    loadOutlineMaterials,
    saveSupplementalViewpoints,
    submitOutlineMaterial,
    reloadArticleMeta,
    createSnapshot,
    restoreSnapshot,
    loadDiff,
    loadHistoryReferences,
    toggleHistoryReferenceSelection,
    updateHistoryReferenceField,
    saveHistoryReferenceSelection,
    addFactCheckEvidenceSource,
    dismissFactCheckEvidenceIssue: dismissFactCheckEvidenceIssueAction,
    loadDeepWritingOpeningPreview,
    sampleDeepWritingStateOpenings,
    sampleDeepWritingPrototypeOpenings,
    publish,
    requestPublishPreview,
    loadPublishPreview,
    refreshPublishPreviewRender,
    closeWechatConnectModal,
    persistPendingPublishIntent,
    clearPendingPublishIntent,
    openWechatConnectModal,
    retryLatestPublish,
    submitWechatConnectionFromEditor,
    resumePendingPublishIntent,
    saveOutcomeSnapshot,
    generateCoverImage,
    selectCoverCandidate,
    saveImagePromptAssets,
    generateInlineImages,
    insertVisualAssets,
    applyLayoutTemplate,
    refreshKnowledgeCard,
    prefetchStageArtifact,
    applyStageArtifact,
    syncOutlineArtifactToNodes,
    saveAudienceSelection,
    saveOutlineSelection,
    saveFactCheckSelection,
    handleAudienceAnalysisSelectReaderLabel,
    handleAudienceAnalysisSelectLanguageGuidance,
    handleAudienceAnalysisSelectBackgroundAwareness,
    handleAudienceAnalysisSelectReadabilityLevel,
    handleAudienceAnalysisSelectCallToAction,
    handleAudienceAnalysisSaveSelection,
    refreshOutlinePlanningMaterials,
    handleOutlinePlanningSupplementalViewpointChange,
    handleOutlinePlanningSaveSupplementalViewpoints,
    handleOutlinePlanningAttachExistingMaterial,
    handleOutlinePlanningSubmitCreateMaterial,
    handleOutlinePlanningSelectTitle,
    handleOutlinePlanningSelectOpeningHook,
    handleOutlinePlanningSelectTargetEmotion,
    handleOutlinePlanningSelectEndingStrategy,
    handleOutlinePlanningSaveSelection,
    updateFactCheckDecision,
    regenerateOutlinePlanningTitleOptions,
    regenerateOutlinePlanningOpeningOptions,
    runDeepWritingOpeningCheck,
    handleFactCheckStageAddEvidenceSource,
    handleFactCheckStageClearEvidenceIssue,
    handleFactCheckStageOpenKnowledgeCard,
    handleFactCheckStageSaveSelection,
  } = buildArticleWorkspaceActionBundle(
    buildArticleWorkspaceActionBundleInput({
      article,
      title,
      markdown,
      status,
      seriesId,
      seriesOptions,
      wechatTemplateId,
      generateBlockedByResearch,
      generateBlockedMessage,
      deepWritingPrototypeOverride,
      deepWritingStateVariantOverride,
      deepWritingArtifact,
      workflow,
      lastSavedRef,
      setSaveState,
      setMessage,
      setHtmlPreview,
      setTitle,
      setStatus: (nextStatus: ArticleStatus | "generating") => setStatus(nextStatus),
      setSeriesId,
      setWechatTemplateId,
      setGenerating,
      setView,
      setMarkdown,
      setGeneratingStageArtifactCode,
      setStageArtifacts,
      updateWorkflow,
      loadingOutlineMaterials,
      supplementalViewpointsDraft,
      outlineMaterialNodeId,
      outlineMaterialFragmentId,
      outlineMaterialUsageMode,
      outlineMaterialTitle,
      outlineMaterialContent,
      outlineMaterialUrl,
      outlineMaterialImageDataUrl,
      outlineMaterialScreenshotInputRef,
      snapshotNote,
      setLoadingOutlineMaterials,
      setSavingOutlineMaterials,
      setOutlineMaterials,
      setSupplementalViewpointsDraft,
      setOutlineMaterialNodeId,
      setNodes,
      setOutlineMaterialFragmentId,
      setOutlineMaterialTitle,
      setOutlineMaterialContent,
      setOutlineMaterialUrl,
      setOutlineMaterialImageDataUrl,
      setOutlineMaterialScreenshotFileName,
      setSnapshots,
      setWorkflow,
      refreshRouter: () => refreshRouter(router),
      setSnapshotNote,
      setLoadingDiffId,
      setDiffState,
      canUseHistoryReferences,
      displayPlanName,
      loadingHistoryReferences,
      selectedHistoryReferences,
      factCheckEvidenceUrl,
      recentFactCheckEvidenceIssues,
      setLoadingHistoryReferences,
      setHistoryReferenceSuggestions,
      setSelectedHistoryReferences,
      setSavingHistoryReferences,
      setAddingFactCheckEvidence,
      setFactCheckEvidenceUrl,
      setKnowledgeCardItems,
      setExpandedKnowledgeCardId,
      setHighlightedKnowledgeCardId,
      setRecentFactCheckEvidenceIssues,
      setFactCheckEvidenceIssue,
      setDeepWritingOpeningPreviewLoadingKey,
      setDeepWritingOpeningPreviews,
      setDeepWritingOpeningCheckLoading,
      selectedConnectionId,
      wechatConnections,
      selectedConnection,
      canShowWechatControls,
      pendingPublishIntent,
      wechatConnectSubmitting,
      continuePublishAfterWechatConnect,
      wechatConnectAccountName,
      wechatConnectOriginalId,
      wechatConnectAppId,
      wechatConnectAppSecret,
      wechatConnectIsDefault,
      setLoadingPublishPreview,
      setPublishPreview,
      setRefreshingPublishPreview,
      setShowWechatConnectModal,
      setContinuePublishAfterWechatConnect,
      setWechatConnectAccountName,
      setWechatConnectOriginalId,
      setWechatConnectAppId,
      setWechatConnectAppSecret,
      setWechatConnectIsDefault,
      setWechatConnectMessage,
      setPendingPublishIntent,
      setWechatConnections,
      setSyncLogs,
      setPublishing,
      setRetryingPublish,
      setSelectedConnectionId,
      setWechatConnectSubmitting,
      listWechatConnectionsAction: async () => await listWechatConnectionsAction() as WechatConnectionItem[],
      listWechatSyncLogsAction: async (nextArticleId: number) =>
        await listWechatSyncLogsAction(nextArticleId) as RecentSyncLogItem[],
      upsertWechatConnectionAction: async (input: Parameters<typeof upsertWechatConnectionAction>[0]) =>
        await upsertWechatConnectionAction(input),
      canUseCoverImageReference,
      coverImageReferenceDataUrl,
      selectedOutcomeWindowCode,
      outcomeReadCount,
      outcomeShareCount,
      outcomeLikeCount,
      outcomeNotes,
      outcomeTargetPackage,
      outcomeHitStatus,
      outcomeReviewSummary,
      outcomeNextAction,
      outcomePlaybookTagsInput,
      outcomeWindows: OUTCOME_WINDOWS,
      selectedTemplate: selectedTemplate ? { name: selectedTemplate.name } : null,
      setSavingOutcomeSnapshot,
      setArticleOutcomeBundle: (value: ArticleOutcomeBundleItem) => setArticleOutcomeBundle(value),
      setSelectedOutcomeWindowCode,
      setGeneratingCover,
      setCoverImageCandidates,
      setCoverImageQuota,
      setImageAssetQuota,
      setSelectingCoverCandidateId,
      setCoverImage,
      setSavingImagePrompts,
      setGeneratingInlineImages,
      setInsertingVisualAssets,
      setImagePrompts: (value: ArticleImagePromptItem[]) => setImagePrompts(value),
      setApplyingLayout,
      generateCoverImageAction,
      selectCoverCandidateAction,
      currentStageArtifact,
      audienceSelectionDraft,
      outlineSelectionDraft,
      factCheckSelectionDraft,
      setRefreshingKnowledgeId,
      refreshKnowledgeCardAction,
      setApplyingStageArtifactCode,
      setSyncingOutlineArtifact,
      setSavingAudienceSelection,
      outlineMaterialCreateMode,
      setAudienceSelectionDraft,
      setOutlineSelectionDraft,
      setFactCheckSelectionDraft,
    }),
  );

  useArticleWorkspaceSyncEffects({
    articleId: article.id,
    articleSeriesId: article.seriesId,
    currentSeriesPlaybook,
    seriesId,
    initialNodes,
    initialFragments,
    initialConnections,
    initialCoverImageCandidates,
    initialImagePrompts,
    initialStageArtifacts,
    initialOutcomeBundle,
    initialWorkflowPendingPublishIntent: initialWorkflow.pendingPublishIntent,
    knowledgeCards,
    currentArticleOutcome,
    currentOutcomeSnapshot,
    currentStageCode: currentStage?.code,
    currentStageArtifactPayload: currentStageArtifact?.payload,
    currentAudienceSelection,
    currentOutlineSelection,
    currentFactCheckSelection,
    outlineMaterials,
    loadingOutlineMaterials,
    canUseHistoryReferences,
    loadingHistoryReferences,
    historyReferenceSuggestionsLength: historyReferenceSuggestions.length,
    selectedHistoryReferencesLength: selectedHistoryReferences.length,
    wechatConnections,
    persistPendingPublishIntent,
    loadOutlineMaterials,
    loadHistoryReferences,
    setKnowledgeCardItems,
    setExpandedKnowledgeCardId,
    setFragmentPool,
    setWechatConnections,
    setCoverImageCandidates,
    setImagePrompts,
    setStageArtifacts,
    setArticleOutcomeBundle: (value) => setArticleOutcomeBundle(value as ArticleOutcomeBundleItem),
    setSelectedOutcomeWindowCode,
    setOutcomeTargetPackage,
    setOutcomeHitStatus,
    setOutcomeReviewSummary,
    setOutcomeNextAction,
    setOutcomePlaybookTagsInput,
    setSeriesPlaybook,
    setLoadingSeriesPlaybook,
    setOutcomeReadCount,
    setOutcomeShareCount,
    setOutcomeLikeCount,
    setOutcomeNotes,
    setNodes,
    setOutlineMaterials,
    setOutlineMaterialNodeId,
    setPendingPublishIntent,
    setRecentFactCheckEvidenceIssues,
    setAudienceSelectionDraft,
    setOutlineSelectionDraft,
    setFactCheckSelectionDraft,
    setSelectedConnectionId,
  });
  useArticleWorkspaceLocalEffects({
    articleId: article.id,
    requestedMainStepCode,
    requestedMainStepHandledRef,
    currentArticleMainStepCode: currentArticleMainStep.code,
    updateWorkflow: (stageCode, mode, silent) => updateWorkflow(stageCode, mode as never, silent),
    resolveRequestedMainStepAccess: resolveMainStepAccess,
    setMessage,
    generating,
    title,
    markdown,
    seriesId,
    wechatTemplateId,
    lastSavedRef,
    articleAutosaveDebounceMs: ARTICLE_AUTOSAVE_DEBOUNCE_MS,
    saveArticleDraft,
    setSaveState,
    setPublishPreview: () => setPublishPreview(null),
    pathname,
    currentSearchParams,
    replaceRoute: (href) => router.replace(href, { scroll: false }),
  });

  const {
    factCheckStagePanelProps,
    prosePolishStagePanelProps,
    outlinePlanningMaterialsPanel,
    outlinePlanningSelectionPanel,
  } = buildArticleWorkspaceStagePanelProps({
    currentStageArtifactPayload: currentStageArtifact?.payload,
    outlineArtifactPayload: outlineArtifact?.payload,
    currentStagePayload,
    factCheckSelectionDraft,
    factCheckEvidenceUrl,
    setFactCheckEvidenceUrl,
    addingFactCheckEvidence,
    handleFactCheckStageAddEvidenceSource,
    factCheckEvidenceIssue,
    handleFactCheckStageClearEvidenceIssue,
    recentFactCheckEvidenceIssues,
    factCheckRetryableCount,
    factCheckRecoveredCount,
    dismissFactCheckEvidenceIssue: dismissFactCheckEvidenceIssueAction,
    updateFactCheckDecision,
    handleFactCheckStageOpenKnowledgeCard,
    savingAudienceSelection,
    handleFactCheckStageSaveSelection,
    prosePolishSelectedTitle,
    prosePolishOutlinePayload,
    prosePolishRegeneratingTitles,
    regenerateOutlinePlanningTitleOptions,
    regenerateOutlinePlanningOpeningOptions,
    prosePolishWeakestLayer,
    editorQualityPanel,
    loadingOutlineMaterials,
    savingOutlineMaterials,
    refreshOutlinePlanningMaterials,
    outlineMaterialReadiness,
    knowledgeCardItems,
    supplementalViewpointsDraft,
    handleOutlinePlanningSupplementalViewpointChange,
    handleOutlinePlanningSaveSupplementalViewpoints,
    outlineMaterialNodeId,
    setOutlineMaterialNodeId,
    outlineMaterialUsageMode,
    setOutlineMaterialUsageMode,
    outlineMaterialFragmentId,
    setOutlineMaterialFragmentId,
    outlineMaterialsNodes: outlineMaterials?.nodes,
    nodes,
    fragmentPool,
    handleOutlinePlanningAttachExistingMaterial,
    outlineMaterialCreateMode,
    setOutlineMaterialCreateMode,
    outlineMaterialTitle,
    setOutlineMaterialTitle,
    outlineMaterialContent,
    setOutlineMaterialContent,
    outlineMaterialUrl,
    setOutlineMaterialUrl,
    outlineMaterialScreenshotInputRef,
    handleOutlineMaterialScreenshotFileChange,
    outlineMaterialScreenshotFileName,
    handleOutlinePlanningSubmitCreateMaterial,
    outlineSelectionDraft,
    generatingStageArtifactCode,
    updatingWorkflowCode,
    handleOutlinePlanningSelectTitle,
    handleOutlinePlanningSelectOpeningHook,
    handleOutlinePlanningSelectTargetEmotion,
    handleOutlinePlanningSelectEndingStrategy,
    handleOutlinePlanningSaveSelection,
  });

  const handleCoverReferenceFileChange = createDataUrlFileChangeHandler({
    onEmpty: () => {
      setCoverImageReferenceDataUrl(null);
    },
    onLoaded: (result) => {
      setCoverImageReferenceDataUrl(result);
    },
  });
  const saveStrategyCard = () => persistStrategyCardDraft(strategyCardDraft);
  const saveEvidenceItems = () => persistEvidenceItems(evidenceDraftItems);
  const copyMarkdown = () =>
    copyTextToClipboard({
      text: markdown,
      onSuccess: () => setMessage("Markdown 已复制到剪贴板"),
      onError: () => setMessage("复制 Markdown 失败"),
    });
  const deleteCurrentArticle = async () => {
    if (!window.confirm("确定删除这篇稿件吗？相关快照与阶段产物会一并移除。")) {
      return;
    }
    const response = await fetch(`/api/articles/${article.id}`, { method: "DELETE" });
    const json = await response.json();
    if (!response.ok || !json.success) {
      setMessage(json.error || "稿件删除失败");
      return;
    }
    startTransition(() => {
      router.push("/articles");
      router.refresh();
    });
  };

  const {
    workspaceLeftRailProps,
    workspaceShellProps,
    workspaceSidebarProps,
    workspaceOverlaysProps,
  } = buildArticleWorkspaceShellBundle({
    article,
    currentArticleMainStep,
    currentStage,
    currentStageAction,
    currentStageArtifact,
    workspaceBlankSlate,
    currentAuthoringPhase,
    setView,
    generatingStageArtifactCode,
    updatingWorkflowCode,
    applyingStageArtifactCode,
    syncingOutlineArtifact,
    syncOutlineArtifactToNodes,
    deepWritingPrototypeOverride,
    setDeepWritingPrototypeOverride,
    deepWritingStateVariantOverride,
    setDeepWritingStateVariantOverride,
    deepWritingOpeningPreviews,
    deepWritingOpeningPreviewLoadingKey,
    deepWritingOpeningCheckLoading,
    generateStageArtifact,
    sampleDeepWritingPrototypeOpenings,
    sampleDeepWritingStateOpenings,
    loadDeepWritingOpeningPreview,
    runDeepWritingOpeningCheck,
    editorDiversityReport,
    seriesInsight,
    effectiveWritingProfile,
    canUseHistoryReferences,
    displayPlanName,
    loadingHistoryReferences,
    savingHistoryReferences,
    loadHistoryReferences,
    selectedHistoryReferences,
    setSelectedHistoryReferences,
    updateHistoryReferenceField,
    saveHistoryReferenceSelection,
    historyReferenceSuggestions,
    toggleHistoryReferenceSelection,
    generating,
    generateBlockedByResearch,
    generateBlockedMessage,
    generate,
    goToResearchStep,
    currentStagePayload,
    audienceSelectionDraft,
    handleAudienceAnalysisSelectReaderLabel,
    handleAudienceAnalysisSelectLanguageGuidance,
    handleAudienceAnalysisSelectBackgroundAwareness,
    handleAudienceAnalysisSelectReadabilityLevel,
    handleAudienceAnalysisSelectCallToAction,
    savingAudienceSelection,
    handleAudienceAnalysisSaveSelection,
    outlinePlanningMaterialsPanel,
    outlinePlanningSelectionPanel,
    factCheckStagePanelProps,
    prosePolishStagePanelProps,
    selectedTemplate,
    applyingLayout,
    applyLayoutTemplate,
    getStageApplyButtonLabel,
    applyStageArtifact,
    researchArtifact,
    strategyTargetReader,
    strategyCoreAssertion,
    strategyWhyNow,
    strategyResearchHypothesis,
    strategyMarketPositionInsight,
    strategyHistoricalTurningPoint,
    saveStrategyCard,
    saveEvidenceItems,
    suggestedEvidenceItems,
    applyResearchWritebackToStrategyCard,
    applyResearchSuggestedEvidence,
    strategyCardIsComplete,
    savedStrategyCardIsComplete,
    strategyCardHasUnsavedChanges,
    strategyCardMissingFields,
    strategyViewMode,
    setStrategyViewMode,
    strategyArchetype,
    setStrategyArchetype,
    strategyTargetPackage,
    setStrategyTargetPackage,
    strategyPublishWindow,
    setStrategyPublishWindow,
    strategyEndingAction,
    setStrategyEndingAction,
    strategySuggestedValues,
    strategyMainstreamBelief,
    setStrategyMainstreamBelief,
    strategyCardDraft,
    savingStrategyCard,
    auditingStrategyCard,
    lockingStrategyCard,
    runStrategyAudit,
    lockStrategyCard,
    strategyFourPointDrafts,
    setStrategyFourPointDrafts,
    reversingStrategyCardDimension,
    applyStrategyFourPointReverseWriteback,
    strategyFirstHandObservation,
    setStrategyFirstHandObservation,
    strategyFeltMoment,
    setStrategyFeltMoment,
    strategyWhyThisHitMe,
    setStrategyWhyThisHitMe,
    strategyRealSceneOrDialogue,
    setStrategyRealSceneOrDialogue,
    strategyWantToComplain,
    setStrategyWantToComplain,
    strategyNonDelegableTruth,
    setStrategyNonDelegableTruth,
    evidenceDraftStats,
    savedEvidenceStats,
    evidenceHasUnsavedChanges,
    savingEvidenceItems,
    taggingEvidenceItems,
    evidenceDraftItems,
    getItemSignature: buildEvidenceItemSignature,
    setShowImaEvidenceDrawer,
    setEvidenceDraftItems,
    toggleEvidenceDraftItem,
    toggleEvidenceDraftHookTag,
    updateEvidenceDraftHookStrength,
    autoTagEvidenceItems,
    status,
    articleOutcomeBundle,
    currentOutcomeSnapshot,
    articleScorecardSummary,
    articleOutcomeAttributionSummary,
    latestSyncLog,
    selectedOutcomeWindowCode,
    setSelectedOutcomeWindowCode,
    selectedSeries,
    loadingSeriesPlaybook,
    seriesPlaybook,
    outcomeReadCount,
    setOutcomeReadCount,
    outcomeShareCount,
    setOutcomeShareCount,
    outcomeLikeCount,
    setOutcomeLikeCount,
    outcomeNotes,
    setOutcomeNotes,
    outcomeTargetPackage,
    setOutcomeTargetPackage,
    outcomeHitStatus,
    setOutcomeHitStatus,
    outcomeExpressionFeedback,
    setOutcomeExpressionFeedback,
    outcomeReviewSummary,
    setOutcomeReviewSummary,
    outcomeNextAction,
    setOutcomeNextAction,
    outcomePlaybookTagsInput,
    setOutcomePlaybookTagsInput,
    savingOutcomeSnapshot,
    saveOutcomeSnapshot,
    title,
    onChangeTitle: setTitle,
    seriesId,
    seriesOptions,
    onChangeSeriesId: setSeriesId,
    saveArticleDraft,
    hasWritingOverride: Boolean(deepWritingPrototypeOverride || deepWritingStateVariantOverride),
    hasDraftContent,
    draftBlankSlate,
    draftStarterOptions,
    draftBlankSlateInspirations,
    markdown,
    setMarkdown,
    hasPreviewContent,
    htmlPreview,
    selectedConnection,
    initialConnections,
    liveLanguageGuardSummary,
    editorialReview,
    reviewBlankSlate,
    message,
    isCollectPhase,
    nodes,
    fragmentPool,
    reloadArticleMeta,
    snapshotNote,
    setSnapshotNote,
    createSnapshot,
    snapshots,
    loadingDiffId,
    loadDiff,
    restoreSnapshot,
    currentArticleLabel,
    currentArticleMainStepDetail: currentArticleMainStepDisplay?.detail || "当前步骤说明暂未生成。",
    saveState,
    theme,
    isFocusMode,
    toggleTheme,
    toggleFocusMode,
    researchStepSummary,
    researchCoverageRibbon,
    currentArticleTask,
    articleMainSteps: guardedArticleMainSteps,
    authoringPhases,
    currentAuthoringPhaseHint,
    view,
    updateWorkflow,
    handleArticleMainStepSelect,
    showCompactSixStepRail,
    showResearchChecklistRail,
    editorStageChecklist,
    planCapabilityHints,
    knowledgeCardItems,
    knowledgeBlankSlate,
    expandedKnowledgeCardId,
    setExpandedKnowledgeCardId,
    highlightedKnowledgeCardId,
    setHighlightedKnowledgeCardId,
    refreshingKnowledgeId,
    refreshKnowledgeCard,
    liveLanguageGuardHits,
    detectedBannedWords,
    visualSuggestion,
    nodeVisualSuggestions,
    saveImagePromptAssets,
    savingImagePrompts,
    generateInlineImages,
    generatingInlineImages,
    insertVisualAssets,
    insertingVisualAssets,
    generateCoverImage,
    coverImageButtonDisabled,
    canGenerateCoverImage,
    coverImageLimitReached,
    coverImageButtonLabel,
    canUseCoverImageReference,
    handleCoverReferenceFileChange,
    coverImageReferenceDataUrl,
    coverImageQuota,
    imageAssetQuota,
    imageAssetStorageLimitReached,
    coverImageCandidates,
    selectCoverCandidate,
    selectingCoverCandidateId,
    coverImage,
    imagePrompts,
    showMobileInspectorEntry,
    setShowMobileInspector,
    canExportPdf,
    copyMarkdown,
    deleteCurrentArticle,
    canShowWechatControls,
    publishing,
    publish,
    wechatTemplateId,
    setWechatTemplateId,
    templates,
    selectedTemplateForPublish: selectedTemplate,
    selectedConnectionId,
    setSelectedConnectionId,
    wechatConnections,
    openWechatConnectModal,
    pendingPublishIntent,
    resumePendingPublishIntent,
    clearPendingPublishIntent,
    loadingPublishPreview,
    hasUnsavedWechatRenderInputs,
    publishPreview,
    loadPublishPreview,
    retryLatestPublish,
    retryingPublish,
    refreshPublishPreviewRender,
    refreshingPublishPreview,
    diffState,
    showMobileInspector,
    showLeftWorkspaceRail,
    showKnowledgeCardsRail,
    showLanguageGuardRail,
    showVisualEngineRail,
    showWechatConnectModal,
    continuePublishAfterWechatConnect,
    closeWechatConnectModal,
    submitWechatConnectionFromEditor,
    wechatConnectAccountName,
    setWechatConnectAccountName,
    wechatConnectOriginalId,
    setWechatConnectOriginalId,
    wechatConnectAppId,
    setWechatConnectAppId,
    wechatConnectAppSecret,
    setWechatConnectAppSecret,
    wechatConnectIsDefault,
    setWechatConnectIsDefault,
    wechatConnectMessage,
    wechatConnectSubmitting,
    showImaEvidenceDrawer,
    appendImaEvidenceItems,
    showDeliveryRail,
    isWritePhase,
    isPolishPhase,
  });

  return (
    <ArticleWorkspaceFrame
      workspaceGridClass={workspaceGridClass}
      showLeftWorkspaceRail={showLeftWorkspaceRail}
      leftRailProps={workspaceLeftRailProps}
      workspaceShellProps={workspaceShellProps}
      workspaceSidebarProps={workspaceSidebarProps}
      workspaceOverlaysProps={workspaceOverlaysProps}
    />
  );
}
