import { formatArticleStatusLabel } from "@/lib/article-status-label";
import { formatWorkspaceViewLabel } from "./authoring-phase";
import { ARTICLE_MAIN_STEPS, type StrategyCardItem } from "./article-workspace-client-data";
import {
  buildWorkspaceLeftRailProps,
  buildWorkspaceOverlaysProps,
  buildWorkspaceShellProps,
  buildWorkspaceSidebarProps,
} from "./article-workspace-frame-builders";
import { buildWorkspaceShellPanels } from "./workspace-shell-panels";
import { buildWorkspaceShellViewSlots } from "./workspace-shell-view-slots";

type BuildArticleWorkspaceShellBundleInput = Record<string, any>;

export function buildArticleWorkspaceShellBundle(input: BuildArticleWorkspaceShellBundleInput) {
  const { resultLeadPanel, workspaceStepPanels } = buildWorkspaceShellPanels({
    currentArticleMainStepCode: input.currentArticleMainStep.code as never,
    artifactProps: {
      isResultStep: input.currentArticleMainStep.code === "result",
      currentStage: input.currentStage as never,
      currentStageAction: input.currentStageAction as never,
      currentStageArtifact: input.currentStageArtifact as never,
      workspaceBlankSlate: input.workspaceBlankSlate as never,
      currentAuthoringDefaultView: input.currentAuthoringPhase.defaultView,
      formatWorkspaceViewLabel,
      onReturnToDefaultView: () => input.setView(input.currentAuthoringPhase.defaultView),
      generatingStageArtifactCode: input.generatingStageArtifactCode,
      updatingWorkflowCode: input.updatingWorkflowCode,
      applyingStageArtifactCode: input.applyingStageArtifactCode,
      showOutlineSyncAction: input.currentStage?.code === "outlinePlanning",
      syncingOutlineArtifact: input.syncingOutlineArtifact,
      onSyncOutlineArtifactToNodes: input.syncOutlineArtifactToNodes,
      prototypeOverride: input.deepWritingPrototypeOverride,
      onSelectPrototype: input.setDeepWritingPrototypeOverride,
      stateVariantOverride: input.deepWritingStateVariantOverride,
      onSelectStateVariant: input.setDeepWritingStateVariantOverride,
      openingPreviews: input.deepWritingOpeningPreviews,
      openingPreviewLoadingKey: input.deepWritingOpeningPreviewLoadingKey,
      openingCheckLoading: input.deepWritingOpeningCheckLoading,
      onGenerateStageArtifact: input.generateStageArtifact as never,
      onSamplePrototypeOpenings: input.sampleDeepWritingPrototypeOpenings,
      onSampleStateOpenings: input.sampleDeepWritingStateOpenings,
      onLoadOpeningPreview: input.loadDeepWritingOpeningPreview,
      onRunOpeningCheck: input.runDeepWritingOpeningCheck,
      editorDiversityReport: input.editorDiversityReport as never,
      seriesInsight: input.seriesInsight as never,
      canUseHistoryReferences: input.canUseHistoryReferences,
      displayPlanName: input.displayPlanName,
      loadingHistoryReferences: input.loadingHistoryReferences,
      savingHistoryReferences: input.savingHistoryReferences,
      onLoadHistoryReferences: input.loadHistoryReferences,
      selectedHistoryReferences: input.selectedHistoryReferences as never,
      setSelectedHistoryReferences: input.setSelectedHistoryReferences as never,
      updateHistoryReferenceField: input.updateHistoryReferenceField,
      onSaveHistoryReferenceSelection: input.saveHistoryReferenceSelection,
      historyReferenceSuggestions: input.historyReferenceSuggestions as never,
      toggleHistoryReferenceSelection: input.toggleHistoryReferenceSelection as never,
      generating: input.generating,
      generateBlockedByResearch: input.generateBlockedByResearch,
      generateBlockedMessage: input.generateBlockedMessage,
      onStartWriting: input.generate,
      onGoToResearch: input.goToResearchStep,
      currentStagePayload: input.currentStagePayload,
      audienceSelection: input.audienceSelectionDraft as never,
      onSelectReaderLabel: input.handleAudienceAnalysisSelectReaderLabel,
      onSelectLanguageGuidance: input.handleAudienceAnalysisSelectLanguageGuidance,
      onSelectBackgroundAwareness: input.handleAudienceAnalysisSelectBackgroundAwareness,
      onSelectReadabilityLevel: input.handleAudienceAnalysisSelectReadabilityLevel,
      onSelectCallToAction: input.handleAudienceAnalysisSelectCallToAction,
      savingAudienceSelection: input.savingAudienceSelection,
      onSaveAudienceSelection: input.handleAudienceAnalysisSaveSelection,
      outlinePlanningMaterialsPanel: input.outlinePlanningMaterialsPanel as never,
      outlinePlanningSelectionPanel: input.outlinePlanningSelectionPanel as never,
      factCheckStagePanelProps: input.factCheckStagePanelProps as never,
      prosePolishStagePanelProps: input.prosePolishStagePanelProps as never,
      selectedTemplate: input.selectedTemplate as never,
      applyingLayout: input.applyingLayout,
      onApplyLayout: input.applyLayoutTemplate,
      getStageApplyButtonLabel: input.getStageApplyButtonLabel as never,
      onApplyStageArtifact: input.applyStageArtifact,
    },
    researchProps: {
      researchArtifact: input.researchArtifact as never,
      currentArticleMainStepCode: input.currentArticleMainStep.code as never,
      strategyTargetReader: input.strategyTargetReader,
      strategyCoreAssertion: input.strategyCoreAssertion,
      strategyWhyNow: input.strategyWhyNow,
      strategyResearchHypothesis: input.strategyResearchHypothesis,
      strategyMarketPositionInsight: input.strategyMarketPositionInsight,
      strategyHistoricalTurningPoint: input.strategyHistoricalTurningPoint,
      generatingStageArtifactCode: input.generatingStageArtifactCode,
      updatingWorkflowCode: input.updatingWorkflowCode,
      applyingStageArtifactCode: input.applyingStageArtifactCode,
      savingStrategyCard: input.savingStrategyCard,
      savingEvidenceItems: input.savingEvidenceItems,
      suggestedEvidenceItemsCount: input.suggestedEvidenceItems.length,
      onGenerateStageArtifact: input.generateStageArtifact as never,
      onApplyResearchWritebackToStrategyCard: input.applyResearchWritebackToStrategyCard,
      onApplyResearchSuggestedEvidence: input.applyResearchSuggestedEvidence,
    },
    strategyProps: {
      strategyCardIsComplete: input.strategyCardIsComplete,
      savedStrategyCardIsComplete: input.savedStrategyCardIsComplete,
      strategyCardHasUnsavedChanges: input.strategyCardHasUnsavedChanges,
      strategyCardMissingFields: input.strategyCardMissingFields,
      strategyViewMode: input.strategyViewMode,
      onChangeStrategyViewMode: input.setStrategyViewMode,
      strategyArchetype: input.strategyArchetype,
      onChangeStrategyArchetype: (value) => input.setStrategyArchetype((value as StrategyCardItem["archetype"]) || null),
      strategyTargetReader: input.strategyTargetReader,
      onChangeStrategyTargetReader: input.setStrategyTargetReader,
      strategyCoreAssertion: input.strategyCoreAssertion,
      onChangeStrategyCoreAssertion: input.setStrategyCoreAssertion,
      strategyWhyNow: input.strategyWhyNow,
      onChangeStrategyWhyNow: input.setStrategyWhyNow,
      strategyTargetPackage: input.strategyTargetPackage,
      onChangeStrategyTargetPackage: input.setStrategyTargetPackage,
      strategyPublishWindow: input.strategyPublishWindow,
      onChangeStrategyPublishWindow: input.setStrategyPublishWindow,
      strategyEndingAction: input.strategyEndingAction,
      onChangeStrategyEndingAction: input.setStrategyEndingAction,
      strategySuggestedValues: input.strategySuggestedValues as never,
      strategyMainstreamBelief: input.strategyMainstreamBelief,
      onChangeStrategyMainstreamBelief: input.setStrategyMainstreamBelief,
      strategyCardDraft: input.strategyCardDraft as never,
      savingStrategyCard: input.savingStrategyCard,
      auditingStrategyCard: input.auditingStrategyCard,
      lockingStrategyCard: input.lockingStrategyCard,
      runStrategyAudit: input.runStrategyAudit,
      lockStrategyCard: input.lockStrategyCard,
      strategyFourPointDrafts: input.strategyFourPointDrafts as never,
      setStrategyFourPointDrafts: input.setStrategyFourPointDrafts as never,
      reversingStrategyCardDimension: input.reversingStrategyCardDimension as never,
      onApplyStrategyFourPointReverseWriteback: input.applyStrategyFourPointReverseWriteback as never,
      strategyResearchHypothesis: input.strategyResearchHypothesis,
      onChangeStrategyResearchHypothesis: input.setStrategyResearchHypothesis,
      strategyMarketPositionInsight: input.strategyMarketPositionInsight,
      onChangeStrategyMarketPositionInsight: input.setStrategyMarketPositionInsight,
      strategyHistoricalTurningPoint: input.strategyHistoricalTurningPoint,
      onChangeStrategyHistoricalTurningPoint: input.setStrategyHistoricalTurningPoint,
      strategyFirstHandObservation: input.strategyFirstHandObservation,
      onChangeStrategyFirstHandObservation: input.setStrategyFirstHandObservation,
      strategyFeltMoment: input.strategyFeltMoment,
      onChangeStrategyFeltMoment: input.setStrategyFeltMoment,
      strategyWhyThisHitMe: input.strategyWhyThisHitMe,
      onChangeStrategyWhyThisHitMe: input.setStrategyWhyThisHitMe,
      strategyRealSceneOrDialogue: input.strategyRealSceneOrDialogue,
      onChangeStrategyRealSceneOrDialogue: input.setStrategyRealSceneOrDialogue,
      strategyWantToComplain: input.strategyWantToComplain,
      onChangeStrategyWantToComplain: input.setStrategyWantToComplain,
      strategyNonDelegableTruth: input.strategyNonDelegableTruth,
      onChangeStrategyNonDelegableTruth: input.setStrategyNonDelegableTruth,
      onSaveStrategyCard: input.saveStrategyCard as never,
    },
    evidenceProps: {
      evidenceDraftStats: input.evidenceDraftStats as never,
      savedEvidenceReady: input.savedEvidenceStats.ready,
      evidenceHasUnsavedChanges: input.evidenceHasUnsavedChanges,
      savingEvidenceItems: input.savingEvidenceItems,
      taggingEvidenceItems: input.taggingEvidenceItems,
      evidenceDraftItems: input.evidenceDraftItems as never,
      suggestedEvidenceItems: input.suggestedEvidenceItems as never,
      getItemSignature: (item) => input.getItemSignature(item),
      setShowImaEvidenceDrawer: input.setShowImaEvidenceDrawer,
      setEvidenceDraftItems: input.setEvidenceDraftItems as never,
      onToggleItem: input.toggleEvidenceDraftItem as never,
      onToggleHookTag: input.toggleEvidenceDraftHookTag,
      onChangeHookStrength: input.updateEvidenceDraftHookStrength,
      onAutoTag: input.autoTagEvidenceItems,
      onSave: input.saveEvidenceItems as never,
    },
    outcomeProps: {
      status: input.status,
      articleOutcomeBundle: input.articleOutcomeBundle as never,
      currentOutcomeSnapshot: input.currentOutcomeSnapshot as never,
      articleScorecardSummary: input.articleScorecardSummary as never,
      articleOutcomeAttributionSummary: input.articleOutcomeAttributionSummary as never,
      latestSyncLog: input.latestSyncLog as never,
      selectedOutcomeWindowCode: input.selectedOutcomeWindowCode,
      onSelectOutcomeWindowCode: input.setSelectedOutcomeWindowCode,
      selectedSeriesSource: input.selectedSeries as never,
      loadingSeriesPlaybook: input.loadingSeriesPlaybook,
      seriesPlaybook: input.seriesPlaybook as never,
      outcomeReadCount: input.outcomeReadCount,
      onChangeOutcomeReadCount: input.setOutcomeReadCount,
      outcomeShareCount: input.outcomeShareCount,
      onChangeOutcomeShareCount: input.setOutcomeShareCount,
      outcomeLikeCount: input.outcomeLikeCount,
      onChangeOutcomeLikeCount: input.setOutcomeLikeCount,
      outcomeNotes: input.outcomeNotes,
      onChangeOutcomeNotes: input.setOutcomeNotes,
      outcomeTargetPackage: input.outcomeTargetPackage,
      onChangeOutcomeTargetPackage: input.setOutcomeTargetPackage,
      outcomeHitStatus: input.outcomeHitStatus,
      onChangeOutcomeHitStatus: input.setOutcomeHitStatus,
      outcomeReviewSummary: input.outcomeReviewSummary,
      onChangeOutcomeReviewSummary: input.setOutcomeReviewSummary,
      outcomeNextAction: input.outcomeNextAction,
      onChangeOutcomeNextAction: input.setOutcomeNextAction,
      outcomePlaybookTagsInput: input.outcomePlaybookTagsInput,
      onChangeOutcomePlaybookTagsInput: input.setOutcomePlaybookTagsInput,
      savingOutcomeSnapshot: input.savingOutcomeSnapshot,
      onSaveOutcomeSnapshot: input.saveOutcomeSnapshot,
    },
  });

  const workspaceShellViewSlots = buildWorkspaceShellViewSlots({
    controlsBarProps: {
      title: input.title,
      onChangeTitle: input.onChangeTitle,
      seriesId: input.seriesId,
      seriesOptions: input.seriesOptions as never,
      onChangeSeriesId: input.onChangeSeriesId,
      onSave: () => input.saveArticleDraft(),
      generating: input.generating,
      generateBlockedByResearch: input.generateBlockedByResearch,
      hasWritingOverride: input.hasWritingOverride,
      onGenerate: input.generate,
      onGoToResearchStep: input.goToResearchStep,
      updatingWorkflow: Boolean(input.updatingWorkflowCode),
    },
    topbarActionsProps: {
      articleId: input.article.id,
      canExportPdf: input.canExportPdf,
      onCopyMarkdown: input.copyMarkdown,
      onDeleteArticle: input.deleteCurrentArticle,
      metadataHref: "#workspace-metadata",
    },
    editViewProps: {
      hasDraftContent: input.hasDraftContent,
      draftBlankSlate: input.draftBlankSlate as never,
      draftStarterOptions: input.draftStarterOptions as never,
      draftBlankSlateInspirations: input.draftBlankSlateInspirations as never,
      markdown: input.markdown,
      onChangeMarkdown: input.setMarkdown,
      onApplyStarterOption: input.setMarkdown,
      onSwitchToWorkspace: () => input.setView("workspace"),
    },
    previewViewProps: {
      hasPreviewContent: input.hasPreviewContent,
      htmlPreview: input.htmlPreview,
      title: input.title,
      authorName: input.selectedSeries?.personaName || undefined,
      selectedConnection: input.selectedConnection as never,
      initialConnections: input.initialConnections as never,
    },
    auditViewProps: {
      markdown: input.markdown,
      hasDraftContent: input.hasDraftContent,
      liveLanguageGuardSummary: input.liveLanguageGuardSummary as never,
      editorialReview: input.editorialReview as never,
      reviewBlankSlate: input.reviewBlankSlate as never,
      onSwitchToEdit: () => input.setView("edit"),
      onSwitchToWorkspace: () => input.setView("workspace"),
    },
    selectedSeries: input.selectedSeries as never,
    message: input.message,
  });

  const workspaceLeftRailProps = buildWorkspaceLeftRailProps({
    isCollectPhase: input.isCollectPhase,
    articleId: input.article.id,
    nodes: input.nodes as never,
    fragments: input.fragmentPool as never,
    onChangeOutlinePanel: input.reloadArticleMeta,
    snapshotNote: input.snapshotNote,
    onChangeSnapshotNote: input.setSnapshotNote,
    onCreateSnapshot: input.createSnapshot,
    snapshots: input.snapshots as never,
    loadingDiffId: input.loadingDiffId,
    onLoadDiff: input.loadDiff,
    onRestoreSnapshot: input.restoreSnapshot,
  });

  const workspaceShellProps = buildWorkspaceShellProps({
    currentArticleLabel: input.currentArticleLabel,
    currentArticleMainStep: input.currentArticleMainStep as never,
    currentArticleMainStepDetail: input.currentArticleMainStepDetail,
    saveState: input.saveState,
    theme: input.theme,
    isFocusMode: input.isFocusMode,
    onToggleTheme: input.toggleTheme,
    onToggleFocusMode: input.toggleFocusMode,
    generateBlockedByResearch: input.generateBlockedByResearch,
    generateBlockedMessage: input.generateBlockedMessage,
    researchStepSummary: input.researchStepSummary as never,
    researchCoverageRibbon: input.researchCoverageRibbon as never,
    currentArticleTask: input.currentArticleTask as never,
    onGoToResearchStep: input.goToResearchStep,
    isUpdatingWorkflow: input.updatingWorkflowCode !== null,
    hideMainStepRail: input.isFocusMode || input.isWritePhase || input.isPolishPhase,
    articleMainSteps: input.articleMainSteps as never,
    onSelectMainStep: (step) => input.handleArticleMainStepSelect(step as never),
    canOpenResultStep: input.status === "published",
    resultLeadPanel,
    authoringPhases: input.authoringPhases as never,
    currentAuthoringPhaseTitle: input.currentAuthoringPhase.title,
    currentAuthoringPhaseHint: input.currentAuthoringPhaseHint,
    onSelectAuthoringPhase: (phase) => {
      input.setView(phase.defaultView);
      void input.updateWorkflow(phase.targetStageCode as never, "set");
    },
    view: input.view,
    onViewChange: input.setView,
    formatWorkspaceViewLabel,
    workspaceShellViewSlots,
    workspaceStepPanels,
  });

  const workspaceSidebarProps = buildWorkspaceSidebarProps({
    isFocusMode: input.isFocusMode,
    showCompactSixStepRail: input.showCompactSixStepRail,
    currentArticleMainStepTitle: input.currentArticleMainStep.title,
    currentArticleMainStepDetail: input.currentArticleMainStepDetail,
    articleMainSteps: input.articleMainSteps as never,
    updatingWorkflow: input.updatingWorkflowCode !== null,
    canOpenResultStep: input.status === "published",
    onSelectMainStep: (stepCode) => {
      const targetStep = ARTICLE_MAIN_STEPS.find((step) => step.code === stepCode);
      if (targetStep) {
        input.handleArticleMainStepSelect(targetStep as never);
      }
    },
    showSnapshotManager: !input.showLeftWorkspaceRail,
    snapshotNote: input.snapshotNote,
    onChangeSnapshotNote: input.setSnapshotNote,
    onCreateSnapshot: input.createSnapshot,
    snapshots: input.snapshots as never,
    loadingDiffId: input.loadingDiffId,
    onLoadDiff: input.loadDiff,
    onRestoreSnapshot: input.restoreSnapshot,
    showResearchChecklistRail: input.showResearchChecklistRail,
    researchStepSummary: input.researchStepSummary as never,
    editorStageChecklist: input.editorStageChecklist as never,
    planCapabilityHints: input.planCapabilityHints as never,
    currentStageTitle: input.currentStage?.title || null,
    stageArtifactsCount: input.stageArtifactsCount,
    articleStatusLabel: input.status === "generating" ? "生成中" : formatArticleStatusLabel(input.status),
    showKnowledgeCardsRail: input.showKnowledgeCardsRail,
    knowledgeCardsRailProps: {
      knowledgeCardItems: input.knowledgeCardItems as never,
      knowledgeBlankSlate: input.knowledgeBlankSlate as never,
      expandedKnowledgeCardId: input.expandedKnowledgeCardId,
      highlightedKnowledgeCardId: input.highlightedKnowledgeCardId,
      refreshingKnowledgeId: input.refreshingKnowledgeId,
      onRefreshKnowledgeCard: input.refreshKnowledgeCard,
      onToggleKnowledgeCard: (cardId, expanded, highlighted) => {
        input.setExpandedKnowledgeCardId(expanded ? null : cardId);
        if (highlighted) {
          input.setHighlightedKnowledgeCardId(null);
        }
      },
    },
    showLanguageGuardRail: input.showLanguageGuardRail,
    languageGuardRailProps: {
      liveLanguageGuardHits: input.liveLanguageGuardHits as never,
      liveLanguageGuardSummary: input.liveLanguageGuardSummary as never,
      detectedBannedWords: input.detectedBannedWords as never,
    },
    showVisualEngineRail: input.showVisualEngineRail,
    visualEngineRailProps: {
      visualSuggestion: input.visualSuggestion,
      nodeVisualSuggestions: input.nodeVisualSuggestions as never,
      onSaveImagePromptAssets: input.saveImagePromptAssets,
      savingImagePrompts: input.savingImagePrompts,
      onGenerateCoverImage: input.generateCoverImage,
      coverImageButtonDisabled: input.coverImageButtonDisabled,
      coverImageButtonVariant: input.canGenerateCoverImage && !input.coverImageLimitReached ? "primary" : "secondary",
      coverImageButtonMuted: !(input.canGenerateCoverImage && !input.coverImageLimitReached),
      coverImageButtonLabel: input.coverImageButtonLabel,
      canUseCoverImageReference: input.canUseCoverImageReference,
      onCoverReferenceFileChange: input.handleCoverReferenceFileChange,
      coverImageReferenceDataUrl: input.coverImageReferenceDataUrl,
      canGenerateCoverImage: input.canGenerateCoverImage,
      coverImageQuota: input.coverImageQuota as never,
      imageAssetQuota: input.imageAssetQuota as never,
      imageAssetStorageLimitReached: input.imageAssetStorageLimitReached,
      coverImageLimitReached: input.coverImageLimitReached,
      coverImageCandidates: input.coverImageCandidates as never,
      onSelectCoverCandidate: input.selectCoverCandidate,
      selectingCoverCandidateId: input.selectingCoverCandidateId,
      coverImage: input.coverImage as never,
      imagePrompts: input.imagePrompts as never,
    },
    showMobileInspectorEntry: input.showMobileInspectorEntry,
    onOpenMobileInspector: () => input.setShowMobileInspector(true),
    showDeliveryRail: input.showDeliveryRail,
    exportActionsRailProps: {
      articleId: input.article.id,
      canExportPdf: input.canExportPdf,
      onCopyMarkdown: input.copyMarkdown as never,
    },
    wechatPublishRailProps: {
      canShowWechatControls: input.canShowWechatControls,
      displayPlanName: input.displayPlanName,
      publishing: input.publishing,
      onPublish: input.publish,
      setupSection: {
        wechatTemplateId: input.wechatTemplateId,
        onChangeWechatTemplateId: input.setWechatTemplateId,
        templates: input.templates as never,
        selectedTemplate: input.selectedTemplateForPublish as never,
        selectedConnectionId: input.selectedConnectionId,
        onChangeSelectedConnectionId: input.setSelectedConnectionId,
        wechatConnections: input.wechatConnections as never,
        selectedConnection: input.selectedConnection as never,
        onOpenWechatConnectModal: () => input.openWechatConnectModal(false),
        pendingPublishIntent: input.pendingPublishIntent as never,
        onResumePendingPublishIntent: input.resumePendingPublishIntent,
        onClearPendingPublishIntent: input.clearPendingPublishIntent,
        publishing: input.publishing,
      },
      previewSection: {
        loadingPublishPreview: input.loadingPublishPreview,
        hasUnsavedWechatRenderInputs: input.hasUnsavedWechatRenderInputs,
        publishPreview: input.publishPreview as never,
        onLoadPublishPreview: input.loadPublishPreview,
        onUpdateWorkflowStage: (stageCode) => {
          void input.updateWorkflow(stageCode as never, "set");
        },
        onRetryLatestPublish: input.retryLatestPublish,
        retryingPublish: input.retryingPublish,
        canRetryPublish: Boolean(input.selectedConnectionId),
        onSwitchToPreview: () => input.setView("preview"),
        onRefreshPublishPreviewRender: input.refreshPublishPreviewRender,
        refreshingPublishPreview: input.refreshingPublishPreview,
        previewFallbackTitle: input.title,
        authorName: input.selectedSeries?.personaName || undefined,
      },
      syncSection: {
        latestSyncLog: input.latestSyncLog as never,
        onRetryLatestPublish: input.retryLatestPublish,
        retryingPublish: input.retryingPublish,
        canRetryPublish: Boolean(input.selectedConnectionId),
      },
    },
    isPolishPhase: input.isPolishPhase,
    diffState: input.diffState as never,
  });

  const workspaceOverlaysProps = buildWorkspaceOverlaysProps({
    mobileInspectorSheetProps: {
      open: input.showMobileInspector,
      currentArticleMainStep: input.currentArticleMainStep as never,
      articleMainSteps: input.articleMainSteps as never,
      currentStage: input.currentStage as never,
      status: input.status,
      showLeftWorkspaceRail: input.showLeftWorkspaceRail,
      snapshotNote: input.snapshotNote,
      onChangeSnapshotNote: input.setSnapshotNote,
      onCreateSnapshot: input.createSnapshot,
      snapshots: input.snapshots as never,
      loadingDiffId: input.loadingDiffId,
      onLoadDiff: input.loadDiff,
      onRestoreSnapshot: input.restoreSnapshot,
      showKnowledgeCardsRail: input.showKnowledgeCardsRail,
      knowledgeCardItems: input.knowledgeCardItems as never,
      showLanguageGuardRail: input.showLanguageGuardRail,
      liveLanguageGuardHits: input.liveLanguageGuardHits as never,
      onSwitchToAudit: () => input.setView("audit"),
      showVisualEngineRail: input.showVisualEngineRail,
      visualSuggestion: input.visualSuggestion,
      hasNodeVisualSuggestions: input.nodeVisualSuggestions.length > 0,
      onSaveImagePromptAssets: input.saveImagePromptAssets,
      savingImagePrompts: input.savingImagePrompts,
      onGenerateCoverImage: input.generateCoverImage,
      coverImageButtonDisabled: input.coverImageButtonDisabled,
      coverImageButtonLabel: input.coverImageButtonLabel,
      coverImageButtonVariant: input.canGenerateCoverImage && !input.coverImageLimitReached ? "primary" : "secondary",
      onClose: () => input.setShowMobileInspector(false),
    },
    wechatConnectModalProps: {
      open: input.showWechatConnectModal,
      continuePublishAfterWechatConnect: input.continuePublishAfterWechatConnect,
      onClose: input.closeWechatConnectModal,
      onSubmit: input.submitWechatConnectionFromEditor as never,
      wechatConnectAccountName: input.wechatConnectAccountName,
      onChangeWechatConnectAccountName: input.setWechatConnectAccountName,
      wechatConnectOriginalId: input.wechatConnectOriginalId,
      onChangeWechatConnectOriginalId: input.setWechatConnectOriginalId,
      wechatConnectAppId: input.wechatConnectAppId,
      onChangeWechatConnectAppId: input.setWechatConnectAppId,
      wechatConnectAppSecret: input.wechatConnectAppSecret,
      onChangeWechatConnectAppSecret: input.setWechatConnectAppSecret,
      wechatConnectIsDefault: input.wechatConnectIsDefault,
      onChangeWechatConnectIsDefault: input.setWechatConnectIsDefault,
      wechatConnectMessage: input.wechatConnectMessage,
      wechatConnectSubmitting: input.wechatConnectSubmitting,
    },
    imaEvidenceSearchDrawerProps: {
      articleId: input.article.id,
      open: input.showImaEvidenceDrawer,
      onClose: () => input.setShowImaEvidenceDrawer(false),
      onImport: input.appendImaEvidenceItems as never,
    },
  });

  return {
    workspaceLeftRailProps,
    workspaceShellProps,
    workspaceSidebarProps,
    workspaceOverlaysProps,
  };
}
