export const STYLE_TEMPLATE_LIBRARY = [
  {
    id: "latepost-minimal",
    name: "晚点极简风",
    description: "偏报道感、低修饰、段落克制，适合商业评论和行业观察。",
    meta: "模板",
    config: {
      schemaVersion: "v2",
      tone: "克制报道",
      paragraphLength: "short",
      titleStyle: "sharp",
      backgroundStyle: "newsprint",
      emphasisStyle: "marker",
      quoteStyle: "news",
      codeBlockStyle: "ink",
      commandBlockStyle: "command",
      dividerStyle: "hairline",
      recommendationStyle: "compact",
      identity: {
        tone: "克制报道",
      },
      layout: {
        paragraphLength: "short",
        backgroundStyle: "newsprint",
        dividerStyle: "hairline",
      },
      typography: {
        titleStyle: "sharp",
        emphasisStyle: "marker",
        quoteStyle: "news",
      },
      blocks: {
        codeBlockStyle: "ink",
        commandBlockStyle: "command",
        recommendationStyle: "compact",
      },
      constraints: {
        bannedPunctuation: ["！！！"],
      },
      bannedPunctuation: ["！！！"],
    },
  },
  {
    id: "huozi-editorial",
    name: "活字新中式",
    description: "强调留白、衬线标题、正文行距宽，适合专栏长文。",
    meta: "版式",
    config: {
      schemaVersion: "v2",
      tone: "留白专栏",
      paragraphLength: "medium",
      titleStyle: "serif",
      backgroundStyle: "scroll",
      emphasisStyle: "underline",
      quoteStyle: "editorial",
      codeBlockStyle: "soft",
      commandBlockStyle: "soft-command",
      dividerStyle: "seal",
      recommendationStyle: "card",
      identity: {
        tone: "留白专栏",
      },
      layout: {
        paragraphLength: "medium",
        backgroundStyle: "scroll",
        dividerStyle: "seal",
      },
      typography: {
        titleStyle: "serif",
        emphasisStyle: "underline",
        quoteStyle: "editorial",
      },
      blocks: {
        codeBlockStyle: "soft",
        commandBlockStyle: "soft-command",
        recommendationStyle: "card",
      },
      constraints: {
        bannedPunctuation: [],
      },
      bannedPunctuation: [],
    },
  },
  {
    id: "anti-buzzwords",
    name: "黑话净化包",
    description: "预置空话与对应替换建议，适合在终稿阶段做语言降噪。",
    meta: "词库",
    config: {
      schemaVersion: "v2",
      tone: "降噪净化",
      paragraphLength: "short",
      titleStyle: "plain",
      backgroundStyle: "paper",
      emphasisStyle: "badge",
      quoteStyle: "note",
      codeBlockStyle: "terminal",
      commandBlockStyle: "terminal",
      dividerStyle: "dots",
      recommendationStyle: "checklist",
      identity: {
        tone: "降噪净化",
      },
      layout: {
        paragraphLength: "short",
        backgroundStyle: "paper",
        dividerStyle: "dots",
      },
      typography: {
        titleStyle: "plain",
        emphasisStyle: "badge",
        quoteStyle: "note",
      },
      blocks: {
        codeBlockStyle: "terminal",
        commandBlockStyle: "terminal",
        recommendationStyle: "checklist",
      },
      constraints: {
        bannedWords: ["赋能", "底层逻辑", "不可否认"],
      },
      bannedWords: ["赋能", "底层逻辑", "不可否认"],
    },
  },
];
